name: tfm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20210324.0=h9c3ff4c_0
  - alsa-lib=1.2.3=h516909a_0
  - altair=4.1.0=py_1
  - anyio=2.2.0=py39hf3d152e_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py39h3811e60_2
  - arrow-cpp=4.0.0=py39h3f173ad_1_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - aws-c-cal=0.4.5=h5ca8eb3_9
  - aws-c-common=0.5.8=h7f98852_0
  - aws-c-event-stream=0.2.7=h832d4c5_2
  - aws-c-io=0.9.4=hfee9f7d_5
  - aws-checksums=0.1.11=hdc257ea_4
  - aws-sdk-cpp=1.8.186=h973185b_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - base58=2.1.0=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - boto3=1.17.64=pyhd8ed1ab_0
  - botocore=1.20.64=pyhd8ed1ab_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2020.12.5=py39hf3d152e_1
  - cffi=1.14.5=py39he32792d_0
  - chardet=4.0.0=py39hf3d152e_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h48d8840_2
  - decorator=5.0.7=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - docopt=0.6.2=py_1
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.15=pyhd8ed1ab_0
  - glib=2.68.1=h9c3ff4c_0
  - glib-tools=2.68.1=h9c3ff4c_0
  - glog=0.4.0=h49b9bf7_3
  - grpc-cpp=1.37.1=h36de60a_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imbalanced-learn=0.8.0=pyhd8ed1ab_0
  - importlib-metadata=4.0.1=py39hf3d152e_0
  - ipykernel=5.5.3=py39hef51801_0
  - ipython=7.23.0=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py39hf3d152e_2
  - jinja2=2.11.3=pyh44b312d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-packaging=0.9.2=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39hf3d152e_0
  - jupyter_server=1.6.4=py39hf3d152e_0
  - jupyterlab=3.0.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.5.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py39h1a9c180_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libclang=11.1.0=default_ha53f305_0
  - libcurl=7.76.1=hc4aaa36_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.1=h3e27bee_0
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.15=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.2=hfd2b0eb_2
  - libprotobuf=3.15.8=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libthrift=0.14.1=he6d91bd_1
  - libtiff=4.2.0=hdc55705_1
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h72842e0_4
  - lightgbm=3.2.1=py39he80948d_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py39h3811e60_3
  - matplotlib=3.3.4=py39hf3d152e_0
  - matplotlib-base=3.3.4=py39h2fa2bec_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py39h3811e60_1003
  - mysql-common=8.0.23=ha770c72_1
  - mysql-libs=8.0.23=h935591d_1
  - nbclassic=0.2.7=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py39hf3d152e_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.3.0=pyha770c72_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.64=hb5efdd6_0
  - numpy=1.20.2=py39hdbf815f_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1k=h7f98852_0
  - orc=1.6.7=heec2584_1
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.2=py39hde0f152_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py39hf95b381_1
  - pip=21.1.1=pyhd8ed1ab_0
  - pipreqs=0.4.10=py_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - protobuf=3.15.8=py39he80948d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=4.0.0=py39h3ebc44c_1_cpu
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeck=0.6.2=pyh44b312d_0
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hf3d152e_7
  - pyqt-impl=5.12.3=py39h0fcd23e_7
  - pyqt5-sip=4.19.18=py39he80948d_7
  - pyqtchart=5.12=py39h0fcd23e_7
  - pyqtwebengine=5.12.1=py39h0fcd23e_7
  - pyrsistent=0.17.3=py39h3811e60_2
  - pysocks=1.7.1=py39hf3d152e_3
  - python=3.9.1=hffdb5ce_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - pyzmq=22.0.3=py39h37b5a0c_1
  - qt=5.12.9=hda022c4_4
  - re2=2021.04.01=h9c3ff4c_0
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - s2n=1.0.5=h9b69904_0
  - s3transfer=0.4.2=pyhd8ed1ab_0
  - scikit-learn=0.24.1=py39h4dfa638_0
  - scipy=1.6.3=py39hee8e79c_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py39hf3d152e_3
  - six=1.15.0=pyh9f0ad1d_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=he1b5a44_3
  - sniffio=1.2.0=py39hf3d152e_1
  - sqlite=3.35.5=h74cdb3f_0
  - statsmodels=0.12.2=py39hce5d2b2_0
  - streamlit=0.81.0=pyhd8ed1ab_0
  - terminado=0.9.4=py39hf3d152e_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.7.0=py39hf3d152e_3
  - toolz=0.11.1=py_0
  - tornado=6.1=py39h3811e60_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=he74cb21_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3deb0d_0
  - watchdog=2.0.3=py39hf3d152e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py39hf3d152e_4
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarg=0.1.9=py_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - filelock==3.0.12
    - gdown==3.13.0
    - xgboost==1.3.3
prefix: /home/adrian/miniconda3/envs/tfm
